/* «Найди и перестрой»: больная система, сначала диагноз, потом перестройка. */
(function () {
  const C = (x = 40, y = 250) => ['client', 'client', x, y];
  const F = () => SD.fmt;
  const by = (g, id) => g.nodes.find(n => n.id === id);
  SD.DIAG = SD.DIAG || {};
  const diag = { t: 'diagnose' };
  const L = o => Object.assign({ tier: 'fix', fix: true, decisions: [], preset: [C()], stretch: { cost: Infinity } }, o);
  const E = [['client', 'lb'], ['lb', 'app'], ['app', 'db']];

  SD.FIXES = [
    L({ id: 'f-shareddb', title: 'Миграция сломала соседей', chips: ['инцидент', 'границы данных'],
      story: 'Команда заказов переименовала колонку — и у команды доставки упал прод. На ретро выяснилось, что так бывает каждый месяц. Ещё база загружена на 130 %, хотя каждый сервис по отдельности нагружает её умеренно.',
      diagnose: { answer: 'shareddb', opts: ['shareddb', 'distmono', 'spof', 'chatty'] },
      traffic: { read: 6000, write: 600 }, allow: ['lb', 'app', 'sql', 'cache', 'queue', 'worker'],
      start: { nodes: [['lb', 'lb', 220, 250], ['orders', 'app', 430, 130, { count: 2 }, 'Заказы'], ['delivery', 'app', 430, 370, { count: 2 }, 'Доставка'], ['db', 'sql', 700, 250, { replicas: 1 }]], edges: [['client', 'lb'], ['lb', 'orders'], ['lb', 'delivery'], ['orders', 'db'], ['delivery', 'db']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'arch', text: 'У каждого сервиса свои данные', not: ['shareddb'] }, { t: 'cost', max: 3000 }],
      hints: [{ text: 'Дай каждому сервису свою базу. Данные соседа — через API или события.', why: 'Тогда схема — внутреннее дело команды.' }],
      solution: { nodes: [['lb', 'lb', 220, 250], ['orders', 'app', 430, 130, { count: 2 }, 'Заказы'], ['delivery', 'app', 430, 370, { count: 2 }, 'Доставка'], ['odb', 'sql', 700, 130, { replicas: 1 }], ['ddb', 'sql', 700, 370, { replicas: 1 }]], edges: [['client', 'lb'], ['lb', 'orders'], ['lb', 'delivery'], ['orders', 'odb'], ['delivery', 'ddb']], note: 'База на сервис: нагрузка и схема разделены.' } }),
    L({ id: 'f-distmono', title: 'Все выкатываются вместе', chips: ['инцидент', 'синхронные цепочки'],
      story: 'Оформление заказа проходит через четыре сервиса подряд. Склад выкатывали 5 минут — и всё это время магазин не принимал заказы. Выкатить сервис цен без остальных тоже нельзя.',
      diagnose: { answer: 'distmono', opts: ['distmono', 'shareddb', 'retrystorm', 'godobject'] },
      traffic: { write: 300, read: 3000 }, features: ['distributed'], allow: ['gateway', 'lb', 'app', 'sql', 'cache', 'queue', 'worker'],
      start: { nodes: [['lb', 'lb', 190, 250], ['front', 'app', 360, 250, { count: 2 }, 'Витрина'], ['orders', 'app', 540, 120, { count: 2 }, 'Заказы'], ['odb', 'sql', 760, 40], ['pricing', 'app', 760, 200, { count: 2 }, 'Цены'], ['pdb', 'sql', 980, 160], ['stock', 'app', 980, 320, { count: 2 }, 'Склад'], ['sdb', 'sql', 1180, 320]],
        edges: [['client', 'lb'], ['lb', 'front'], ['front', 'orders'], ['orders', 'odb'], ['orders', 'pricing'], ['pricing', 'pdb'], ['pricing', 'stock'], ['stock', 'sdb']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'arch', text: 'Нет длинных синхронных цепочек', not: ['distmono'] },
        { t: 'custom', text: 'Склад на выкатке, а заказы принимаются', fn: (g, res, lv) => { const s = by(g, 'stock'); if (!s) return { ok: true, detail: 'склада нет в цепочке' }; const r = SD.sim.run(lv, g, { down: { stock: s.props.count } }); const w = r.kinds.write ? r.kinds.write.success : 0; return { ok: w >= 0.99, detail: `оформление ${F().pct(w)}` }; } }],
      hints: [{ text: 'Оформление должно завершаться в «Заказах». Шаги цен и склада — сагой через брокер: выбери у «Заказов» сагу и добавь Заказы → Брокер.', why: 'Асинхронные шаги не держат пользователя и не падают вместе с соседями.' }],
      solution: { nodes: [['lb', 'lb', 190, 250], ['front', 'app', 360, 250, { count: 2 }, 'Витрина'], ['orders', 'app', 540, 120, { count: 2, txMode: 'saga' }, 'Заказы'], ['odb', 'sql', 760, 40], ['q', 'queue', 540, 380, { count: 3, acks: 'all', retries: true }], ['pricing', 'app', 760, 200, { count: 2 }, 'Цены'], ['pdb', 'sql', 980, 160], ['stock', 'app', 980, 320, { count: 2 }, 'Склад'], ['sdb', 'sql', 1180, 320]],
        edges: [['client', 'lb'], ['lb', 'front'], ['front', 'orders'], ['orders', 'odb'], ['orders', 'q'], ['orders', 'pricing'], ['pricing', 'pdb'], ['orders', 'stock'], ['stock', 'sdb']], note: 'Заказы оркестрируют сагу: шаги идут через брокер.' } }),
    L({ id: 'f-retrystorm', title: 'Сервис не может подняться', chips: ['инцидент', 'повторы'],
      story: 'Рекомендации упали на минуту из-за пика. После перезапуска они снова падают, и так уже час. В логах — в три раза больше запросов, чем приходит пользователей.',
      diagnose: { answer: 'retrystorm', opts: ['retrystorm', 'stampede', 'notimeout', 'spof'] },
      traffic: { read: 4000 }, hotSetGb: 8, allow: ['lb', 'app', 'cache', 'sql', 'nosql'],
      start: { nodes: [['lb', 'lb', 210, 250], ['front', 'app', 400, 250, { count: 4 }, 'Витрина'], ['cat', 'app', 640, 130, { count: 2 }, 'Каталог'], ['cache', 'cache', 880, 70], ['db', 'sql', 880, 200], ['recs', 'app', 640, 390, { count: 1 }, 'Рекомендации'], ['rdb', 'nosql', 880, 390]],
        edges: [['client', 'lb'], ['lb', 'front'], ['front', 'cat'], ['cat', 'cache'], ['cat', 'db'], ['front', 'recs', { retries: 3 }], ['recs', 'rdb']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'custom', text: 'Повторы не раздувают нагрузку', fn: (g, res) => { const storm = Object.values(res.edges).some(e => e.info && e.info.amp > 1.3); return { ok: !storm, detail: storm ? 'есть связь с раздуванием > ×1,3' : 'шторма нет' }; } }],
      hints: [{ text: 'На связи Витрина → Рекомендации: пауза с джиттером, 1 повтор, circuit breaker и fallback. Или добавь рекомендациям мощности.', why: 'Повторы без паузы умножают нагрузку на больной сервис.' }],
      solution: { nodes: [['lb', 'lb', 210, 250], ['front', 'app', 400, 250, { count: 4 }, 'Витрина'], ['cat', 'app', 640, 130, { count: 2 }, 'Каталог'], ['cache', 'cache', 880, 70], ['db', 'sql', 880, 200], ['recs', 'app', 640, 390, { count: 1 }, 'Рекомендации'], ['rdb', 'nosql', 880, 390]],
        edges: [['client', 'lb'], ['lb', 'front'], ['front', 'cat'], ['cat', 'cache'], ['cat', 'db'], ['front', 'recs', { timeout: 300, retries: 1, backoff: 'exp', cb: true, fallback: true }], ['recs', 'rdb']], note: 'Предохранитель останавливает шторм, fallback сохраняет страницу.' } }),
    L({ id: 'f-spof', title: 'Ночная перезагрузка', chips: ['инцидент', 'резервирование'],
      story: 'Облако перезагрузило один сервер ради обновления ядра — и сервис лежал 12 минут. Потом то же случилось с базой.',
      diagnose: { answer: 'spof', opts: ['spof', 'notimeout', 'shareddb', 'stampede'] },
      traffic: { read: 2000, write: 200 }, allow: ['lb', 'app', 'sql', 'cache'],
      start: { nodes: [['app', 'app', 320, 250, { count: 1 }], ['db', 'sql', 580, 250]], edges: [['client', 'app'], ['app', 'db']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'survive', types: 'all' }, { t: 'cost', max: 2000 }],
      hints: [{ text: 'Два сервера за балансировщиком и реплика у базы для failover.', why: 'N+1: любой один узел может уйти без простоя.' }],
      solution: { nodes: [['lb', 'lb', 220, 250], ['app', 'app', 420, 250, { count: 2 }], ['db', 'sql', 660, 250, { replicas: 1 }]], edges: E, note: 'Нет компонента в единственном экземпляре.' } }),
    L({ id: 'f-dualwrite', title: 'Пропавшие чеки', chips: ['инцидент', 'согласованность'],
      story: 'Раз в несколько дней клиент оплатил, а чек не пришёл. Платёж в базе есть, а события в Kafka нет. Обычно это совпадает с выкаткой сервиса.',
      diagnose: { answer: 'dualwrite', opts: ['dualwrite', 'retrystorm', 'hotpartition', 'oltpreports'] },
      traffic: { write: 600, read: 1500 }, features: ['payments'],
      job: { from: 'write', label: 'отправка чека', ms: 100, conc: 50, target: 'external' }, ext: { name: 'ОФД', ms: 100, cap: 3000, fail: 0 },
      allow: ['lb', 'app', 'sql', 'queue', 'worker', 'cdc'], preset: [C(), ['ext', 'external', 1000, 420, {}, 'ОФД']],
      start: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 2 }], ['db', 'sql', 680, 130], ['q', 'queue', 680, 360, { count: 3, acks: 'all', retries: true }], ['w', 'worker', 900, 360, { count: 2 }]], edges: [...E, ['app', 'q'], ['q', 'w'], ['w', 'ext']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'durable' }],
      hints: [{ text: 'Transactional outbox у сервиса или CDC из базы вместо прямой публикации.', why: 'Событие должно появляться в той же транзакции, что и платёж.' }],
      solution: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 2, outbox: true }], ['db', 'sql', 680, 130], ['q', 'queue', 680, 360, { count: 3, acks: 'all', retries: true }], ['w', 'worker', 900, 360, { count: 2 }]], edges: [...E, ['app', 'q'], ['q', 'w'], ['w', 'ext']], note: 'Outbox убирает двойную запись.' } }),
    L({ id: 'f-hotpartition', title: 'Один шард горит', chips: ['инцидент', 'шардирование'],
      story: 'Шесть шардов, а загружен один — на 480 %, остальные пять почти простаивают. Добавление шардов не помогает.',
      diagnose: { answer: 'hotpartition', opts: ['hotpartition', 'spof', 'stampede', 'chatty'] },
      traffic: { write: 5000, read: 2000 }, allow: ['lb', 'app', 'sql'],
      start: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 5 }], ['db', 'sql', 680, 250, { shards: 6, shardKey: 'range' }]], edges: E },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'latency', kind: 'write', max: 100 }],
      hints: [{ text: 'Открой базу и посмотри на ключ шардирования: по дате все новые записи попадают в один шард.', why: 'Ключ должен иметь высокую кардинальность и равномерное распределение: hash(user_id).' }],
      solution: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 5 }], ['db', 'sql', 680, 250, { shards: 6, shardKey: 'hash' }]], edges: E, note: 'Хэш раскладывает записи равномерно.' } }),
    L({ id: 'f-oltpreports', title: 'Тормоза по понедельникам', chips: ['инцидент', 'аналитика'],
      story: 'Каждый понедельник в 9:00 покупатели получают ошибки. В это время отдел продаж открывает 50 дашбордов, которые считают выручку по всей истории заказов.',
      diagnose: { answer: 'oltpreports', opts: ['oltpreports', 'stampede', 'spof', 'notimeout'] },
      traffic: { write: 600, read: 4000, report: 50 }, hotSetGb: 8, allow: ['lb', 'app', 'cache', 'sql', 'queue', 'etl', 'olap', 'cdc'],
      start: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 3 }], ['cache', 'cache', 680, 130], ['db', 'sql', 680, 360]], edges: [...E, ['app', 'cache']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'latency', kind: 'read', max: 80 }],
      hints: [{ text: 'Отчёты нужно увести с primary: отдельные реплики под отчёты или аналитическое хранилище с конвейером.', why: 'Агрегат по всей истории занимает ресурсы, нужные покупкам.' }],
      solution: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 3 }], ['cache', 'cache', 680, 60], ['db', 'sql', 680, 200], ['etl', 'etl', 900, 200, { mode: 'hourly' }], ['olap', 'olap', 1100, 200]], edges: [...E, ['app', 'cache'], ['db', 'etl'], ['etl', 'olap'], ['app', 'olap']], note: 'Дашборды читают ClickHouse, который раз в час наполняется из базы.' } }),
    L({ id: 'f-notimeout', title: 'Магазин лёг из-за адресов', chips: ['инцидент', 'таймауты'],
      story: 'Внешний сервис проверки адресов начал отвечать за 3 секунды. Через пять минут перестал открываться весь магазин, хотя адреса нужны только при оформлении.',
      diagnose: { answer: 'notimeout', opts: ['notimeout', 'retrystorm', 'shareddb', 'hotpartition'] },
      traffic: { write: 500, read: 4000 }, hotSetGb: 8,
      job: { from: 'write', label: 'проверка адреса', ms: 3000, conc: 50, target: 'external' }, ext: { name: 'Сервис адресов', ms: 3000, cap: 5000, fail: 0 },
      allow: ['lb', 'app', 'cache', 'sql', 'queue', 'worker'], preset: [C(), ['ext', 'external', 900, 420, {}, 'Сервис адресов']],
      start: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 3 }], ['cache', 'cache', 680, 100], ['db', 'sql', 680, 230]], edges: [...E, ['app', 'cache'], ['app', 'ext']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'latency', kind: 'read', max: 100 }],
      hints: [{ text: 'Таймаут 300 мс и fallback на связи Сервис → Сервис адресов («проверим позже»). Или вынеси проверку в фон через брокер.', why: 'Медленная зависимость не должна занимать потоки, нужные всем остальным запросам.' }],
      solution: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 3 }], ['cache', 'cache', 680, 100], ['db', 'sql', 680, 230]], edges: [...E, ['app', 'cache'], ['app', 'ext', { timeout: 300, cb: true, fallback: true }]], note: 'Таймаут и предохранитель изолируют медленную зависимость.' } }),
    L({ id: 'f-stampede', title: 'После перезапуска Redis', chips: ['инцидент', 'кэш'],
      story: 'Плановый перезапуск единственного узла Redis — и база легла на 10 минут. В обычное время она загружена на 20 %.',
      diagnose: { answer: 'stampede', opts: ['stampede', 'hotpartition', 'retrystorm', 'oltpreports'] },
      traffic: { read: 15000, write: 200 }, hotSetGb: 8, allow: ['lb', 'app', 'cache', 'sql'],
      start: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 8 }], ['cache', 'cache', 680, 130, { mem: 16 }], ['db', 'sql', 680, 360]], edges: [...E, ['app', 'cache']] },
      goals: [diag, { t: 'success', min: 0.999 }, { t: 'survive', types: ['cache'] }],
      hints: [{ text: 'Кэш не должен быть одним узлом: два узла в режиме реплик переживут перезапуск любого.', why: 'Без кэша вся нагрузка разом падает на базу, которая к этому не готова.' }],
      solution: { nodes: [['lb', 'lb', 230, 250], ['app', 'app', 430, 250, { count: 8 }], ['cache', 'cache', 680, 130, { mem: 16, count: 2, cluster: 'replicated', stampede: true }], ['db', 'sql', 680, 360]], edges: [...E, ['app', 'cache']], note: 'Реплика кэша и single-flight.' } })
  ];
})();
